# https://github.com/wesley-a-leung/Resources/blob/master/.github/workflows/build.yml
# Thanks Wesley
name: build
on: [push, pull_request]
jobs:
  check-lines:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check lines
        run: find "Content/" -type f -exec python3 Scripts/check_lines.py {} +
  compile-cpp:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cpp-version: [ c++11, c++14, c++17, c++20 ]
    steps:
      - uses: actions/checkout@v2
      - name: Check version
        run: |
          g++-10 --version
      - name: Compile
        run: find "Content/" \( -iname \*.cpp -o -iname \*.h \) -exec Scripts/Compile.sh "g++-10 -std=${{ matrix.cpp-version }} -Wall -Wextra -fsyntax-only" {} +